#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install yadm

echo "Installing dotfiles"
yadm clone https://github.com/pimenovoleg/dotfiles.git --no-bootstrap

# check if class is available and set it
if [ $# -gt 0 ]; then
  yadm config local.class $1
fi

# let yadm do the rest
yadm alt
yadm bootstrap
